AWSTemplateFormatVersion: '2010-09-09'

Description: 'This template creates rds database with mysql engine in private subnets for Wordtris.'

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: Export VPC Stack Name
        Parameters:
          - ExportVpcStackName
      -
        Label:
          default: Database Parameters
        Parameters:
          - WordtrisDatabaseInstanceIdentifier
          - WordtrisDatabase
          - DatabaseUser
          - DatabasePassword
          - DatabaseBackupRetentionPeriod
          - DatabaseAllocatedStorage
          - DatabaseInstanceClass
          - MultiAZDatabase

Parameters:
  ExportVpcStackName:
    Description: The name of the vpc stack that exports values
    Type: String

  WordtrisDatabaseInstanceIdentifier:
    AllowedPattern: '[a-zA-z][a-zA-Z0-9]*'
    ConstraintDescription: Must begin with a letter and contain alpha numeric characters
    Default: mysqldb
    Description: Database identifier name
    MaxLength: 60
    MinLength: 1
    Type: String

  WordtrisDatabase:
    AllowedPattern: '[a-zA-z][a-zA-Z0-9]*'
    ConstraintDescription: Must begin with a letter and contain alpha numeric characters
    Default: wordtris_db
    Description: MySQL database name
    MaxLength: 64
    MinLength: 1
    Type: String

  DatabaseUser:
    AllowedPattern: '[a-zA-z][a-zA-Z0-9]*'
    ConstraintDescription: Must begin with a letter and contain alpha numeric characters
    Default: wordtris
    Description: User name for database access
    MaxLength: 16
    MinLength: 1
    NoEcho: true
    Type: String

  DatabasePassword:
    AllowedPattern: '[a-zA-Z0-9]*'
    ConstraintDescription: Must contain only alpha numeric characters
    Default: yXpVH0HJSz08
    Description: Password for MySQL database access
    MaxLength: 41
    MinLength: 8
    NoEcho: true
    Type: String

  DatabaseBackupRetentionPeriod:
    ConstraintDescription: Database backup retention period must be between 0 and 35
    Default: 0
    Description: The number of days for which automatic DB snapshots are retained
    MaxValue: 35
    MinValue: 0
    Type: Number

  DatabaseAllocatedStorage:
    ConstraintDescription: Must be between 5 and 1024b
    Default: 20
    Description: The size of the database (Gb)
    MaxValue: 1024
    MinValue: 5
    Type: Number

  DatabaseInstanceClass:
    AllowedValues:
      - db.t1.micro
      - db.t2.micro
      - db.m1.small
      - db.m1.medium
      - db.m1.large
      - db.t4g.micro
    ConstraintDescription: Must select a valid database instance type
    Default: db.t4g.micro
    Description:  The database instance type
    Type: String

  MultiAZDatabase:
    AllowedValues:
      - true
      - false
    ConstraintDescription: Must be either true or false
    Default: false
    Description: Creates a Multi-AZ NtSQL Amazon RDS database instance
    Type: String

Resources:
  # Create Security Group for the DataBase
  DataBaseSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable database access only from the web server
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          SourceSecurityGroupId:
            Fn::ImportValue: !Sub ${ExportVpcStackName}-WebServerSecurityGroup
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: !Sub
            - ${BastionPrivateIp}/32
            - BastionPrivateIp:
                Fn::ImportValue: BastionPrivateIp
      Tags:
        - Key: Name
          Value: Wordtris Security Group for the database
      VpcId:
        Fn::ImportValue: !Sub ${ExportVpcStackName}-VPC

  DatabaseSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for RDS database
      SubnetIds:
        - Fn::ImportValue: !Sub ${ExportVpcStackName}-PrivateSubnet3
        - Fn::ImportValue: !Sub ${ExportVpcStackName}-PrivateSubnet4
      Tags:
        - Key: Name
          Value: database subnets

  DatabaseInstance:
    Type: AWS::RDS::DBInstance
    DependsOn:
      - DataBaseSecurityGroup
    Properties:
      AllocatedStorage: !Ref DatabaseAllocatedStorage
      AvailabilityZone:
        Fn::Select: [ 0, { Fn::GetAZs: '' } ]
      BackupRetentionPeriod: !Ref DatabaseBackupRetentionPeriod
      DBInstanceClass: !Ref DatabaseInstanceClass
      DBInstanceIdentifier: !Ref WordtrisDatabaseInstanceIdentifier
      DBName: !Ref WordtrisDatabase
      DBSubnetGroupName: !Ref DatabaseSubnetGroup
      Engine: MySQL
      EngineVersion: 8.0
      MasterUsername: !Ref DatabaseUser
      MasterUserPassword: !Ref DatabasePassword
      MultiAZ: !Ref MultiAZDatabase
      VPCSecurityGroups:
        - !Ref DataBaseSecurityGroup

Outputs:
  DatabaseSecurityGroup:
    Description: Database Security Group ID
    Export:
      Name: !Sub ${AWS::StackName}-DatabaseSecurityGroup
    Value: !Ref DataBaseSecurityGroup

  DatabaseConnection:
    Description: Wordtris database endpoint
    Value: !Join ['', ['jdbc:mysql://', !GetAtt 'DatabaseInstance.Endpoint.Address', ':3306/', !Ref 'WordtrisDatabase']]
    Export:
      Name: !Join [ ':', [ !Ref 'AWS::StackName', 'ComponentDBUri' ] ]